# Generated by Django 4.0.3 on 2022-04-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                               should be treated as active.                                                Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
