# Generated by Django 4.0.3 on 2022-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0002_alter_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryregistration',
            name='initial',
            field=models.BooleanField(default=True, help_text='Designates whether this user                                             is newly created and its                                             email activation is still pending', verbose_name='Initial'),
        ),
    ]
