# Generated by Django 4.0.3 on 2022-04-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0003_libraryregistration_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryregistration',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='libraryregistration',
            name='password2',
        ),
    ]
