# Generated by Django 4.0.3 on 2022-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0004_remove_libraryregistration_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryregistration',
            name='initial',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                             is newly created and its                                             email activation is still pending', verbose_name='Initial'),
        ),
    ]
