# Generated by Django 4.0.3 on 2022-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0005_alter_libraryregistration_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryregistration',
            name='initial',
        ),
        migrations.AddField(
            model_name='libraryregistration',
            name='is_initial',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                                is newly created and its                                                email activation is still pending', verbose_name='Initial'),
        ),
        migrations.AddField(
            model_name='libraryregistration',
            name='is_invited',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                                has received activation link on its email', verbose_name='Invited'),
        ),
    ]
