# Generated by Django 4.0.4 on 2022-05-05 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0005_libraryregistration_activation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('select_no_of_weeks', models.CharField(choices=[('1', 'One Week'), ('2', 'Two Weeks'), ('3', 'Three Weeks'), ('4', 'Four Weeks')], max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
