# Generated by Django 4.0.4 on 2022-05-05 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0006_bookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='select_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagement.bookdata'),
        ),
    ]
