# Generated by Django 4.0.3 on 2022-04-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0006_remove_libraryregistration_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_invited',
            field=models.BooleanField(default=True, help_text='Designates whether this user                                                has received activation link on its email', verbose_name='Invited'),
        ),
    ]
