# Generated by Django 4.0.4 on 2022-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0007_student_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_initial',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                                is newly created and its                                                email activation is still pending', verbose_name='Initial'),
        ),
    ]
