# Generated by Django 4.0.4 on 2022-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0007_alter_bookrequest_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether your book issue request                                                is approved or not', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Designates whether your book issue request                                                is rejected or not', verbose_name='Rejected'),
        ),
    ]
