# Generated by Django 4.0.4 on 2022-04-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0008_student_is_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryregistration',
            name='open_link',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                               has clicked on activation link                                               sent on his/her email', verbose_name='Opened Link'),
        ),
        migrations.AddField(
            model_name='student',
            name='open_link',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                               has clicked on activation link                                               sent on his/her email', verbose_name='Opened Link'),
        ),
    ]
