# Generated by Django 4.0.4 on 2022-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0008_issuebook_is_approved_issuebook_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='Designates whether your book issue request                                                is still pending or not', verbose_name='Request Pending'),
        ),
    ]
