# Generated by Django 4.0.4 on 2022-05-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0011_issuebook_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='is_subscription_active',
            field=models.BooleanField(default=False, help_text='Designates whether your book subscription is                                                active or not', verbose_name='Subscription Active'),
        ),
    ]
