# Generated by Django 4.0.4 on 2022-05-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0012_issuebook_is_subscription_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
