# Generated by Django 4.0.4 on 2022-05-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0013_delete_bookrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='return_date',
            new_name='expected_return_date',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='actual_return_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='request_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
