# Generated by Django 4.0.4 on 2022-05-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0014_rename_return_date_issuebook_expected_return_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='issue_date',
            new_name='review_date',
        ),
    ]
