# Generated by Django 4.0.4 on 2022-05-11 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0015_rename_issue_date_issuebook_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user                                               should be treated as active.                                                Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_invited', models.BooleanField(default=False, help_text='Designates whether this user                                                has received activation link on its email', verbose_name='Invited')),
                ('is_initial', models.BooleanField(default=True, help_text='Designates whether this user                                                is newly created and its                                                email activation is still pending', verbose_name='Initial')),
                ('open_link', models.BooleanField(default=False, help_text='Designates whether this user                                               has clicked on activation link                                               sent on his/her email', verbose_name='Opened Link')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user                                              is a staff or not', verbose_name='staff status')),
                ('activation_link', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
