# Generated by Django 4.0.4 on 2022-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0016_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='select_no_of_weeks',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='select_no_of_days',
            field=models.IntegerField(default=7, max_length=10, null=True),
        ),
    ]
